PracticalTwelve/Controllers/EmployeeController.cs
using PracticalTwelve.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticalTwelve.Controllers
{
    public class EmployeeController : Controller
    {
        // GET: Employee
        public ActionResult Index()
        {
            List<Employee> employees = EmployeeAccessLayer.GetEmployees();

            return View(employees);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        [HttpPost]
        public ActionResult Create(Employee employee)
        {
            try
            {
                bool IsAdded = EmployeeAccessLayer.AddEmployee(employee);
                if(IsAdded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
					return View();
				}
            }
            catch
            {
                return View();
            }
        }

        public ActionResult UpdateFName()
        {
            EmployeeAccessLayer.UpdateFirstEmployeeName();
            return RedirectToAction("Index");
        }
		public ActionResult UpdateMName()
		{
			EmployeeAccessLayer.UpdateMiddleEmployeeName();
			return RedirectToAction("Index");
		}
		public ActionResult Delete()
		{
			EmployeeAccessLayer.DeleteEmployee();
			return RedirectToAction("Index");
		}
		public ActionResult DeleteAllEmployee()
		{
			EmployeeAccessLayer.DeleteAllEmployee();
			return RedirectToAction("Index");
		}
		public ActionResult InsertEmployee()
		{
			EmployeeAccessLayer.InsertEmployeeData();
			return RedirectToAction("Index");
		}

	}
}

PracticalTwelve/Controllers/Test2Controller.cs
using PracticalTwelve.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PracticalTwelve.Controllers
{
    public class Test2Controller : Controller
    {
        // GET: Test2
        public ActionResult Index()
        {
            List<Test2Employee> test2Employees = Test2EmployeeAccessLayer.GetEmployees();
            return View(test2Employees);
        }
		// GET: Employee/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Employee/Create
		[HttpPost]
		public ActionResult Create(Test2Employee employee)
		{
			try
			{
				bool IsAdded = Test2EmployeeAccessLayer.AddEmployee(employee);
				if (IsAdded)
				{
					return RedirectToAction("Index");
				}
				else
				{
					return View();
				}
			}
			catch
			{
				return View();
			}
		}

		public ActionResult GetEmployee()
		{
			List<Test2Employee> test2Employees = Test2EmployeeAccessLayer.GetEmployeesBasedOnAge();
			return View(test2Employees);
		}

		public ActionResult GetTotalEmployeeSalary()
		{
			decimal TotalSalary = Test2EmployeeAccessLayer.GetTotalSalary();
			TempData["TotalSalary"] = $"Total Salary : {TotalSalary}";
			return RedirectToAction("Index");
		}

		public ActionResult MiddleNameNullCount()
		{
			int Count = Test2EmployeeAccessLayer.GetMiddleNameNullCount();
			TempData["Count"] = $"Total {Count} Employee without middle name";
			return RedirectToAction("Index");
		}
		public ActionResult InsertEmployee()
		{
			Test2EmployeeAccessLayer.InsertEmployeeData();
			return RedirectToAction("Index");
		}
		public ActionResult DeleteAllEmployee()
		{
			Test2EmployeeAccessLayer.DeleteAllEmployees();
			return RedirectToAction("Index");
		}
	}
}

PracticalTwelve/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Practical 12", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Test 1", "Index", "Employee", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Test 2", "Index", "Test2", new { area = "" }, new { @class = "nav-link" })</li>
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>*@
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <footer>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>